Fix possible out of memory exception
Rudimentary but works for now.

Since all image files are cached in map after
some time it will eat to much memory and cause
java.lang.OutOfMemoryError: Java heap space

This is very basic fix, later need to see how to add some logic and
keep at least some files close to the current file that is on display.